azs:
- name: z1
  cloud_properties:
    zone: europe-west2-a
- name: z2
  cloud_properties:
    zone: europe-west2-b
- name: z3
  cloud_properties:
    zone: europe-west2-c

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved: [10.0.0.2-10.0.0.9]
    azs:
    - z1
    - z2
    - z3
    dns:
    - 8.8.8.8
    - 8.8.4.4
    static:
    - 10.0.0.12
    - 10.0.0.16
    - 10.0.0.20
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: bosh-europe-west2
      tags:
      - internal

compilation:
  workers: 1
  network: default
  az: z1
  vm_type: compilation
  reuse_compilation_vms: true

vm_types:
- name: g1-small
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
